# Generated by Django 4.1.2 on 2022-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='add_task',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
