# Generated by Django 4.1.2 on 2022-10-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_alter_add_task_end_date_alter_add_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='add_task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
