# Generated by Django 4.1.2 on 2022-10-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_alter_add_task_end_date_alter_add_task_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='task_discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
