# Generated by Django 4.1.2 on 2022-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_alter_add_task_task_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_task',
            name='created_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
