# Generated by Django 4.1.2 on 2022-10-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0006_rename_add_task_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_time',
        ),
    ]
