# Generated by Django 4.1.2 on 2022-10-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0007_remove_task_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='end_time',
        ),
    ]
