# Generated by Django 4.1.2 on 2022-10-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0008_remove_task_end_date_remove_task_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
